/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 72
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 14
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym_continuation_line = 2,
  aux_sym_comment_token1 = 3,
  aux_sym_comment_token2 = 4,
  anon_sym_pg = 5,
  anon_sym_COLON = 6,
  aux_sym_page_range_token1 = 7,
  anon_sym_tp = 8,
  aux_sym_title_page_token1 = 9,
  anon_sym_st = 10,
  aux_sym_section_title_token1 = 11,
  aux_sym_section_title_token2 = 12,
  anon_sym_tb = 13,
  anon_sym_bt = 14,
  anon_sym_r = 15,
  anon_sym_ref = 16,
  anon_sym_ref_PLUS = 17,
  aux_sym_reference_plus_token1 = 18,
  anon_sym_v = 19,
  aux_sym_versical_token1 = 20,
  anon_sym_pb = 21,
  aux_sym_page_break_token1 = 22,
  anon_sym_l = 23,
  anon_sym_button = 24,
  anon_sym_lords_prayer = 25,
  sym_source_file = 26,
  sym__line = 27,
  sym_comment = 28,
  sym_page_range = 29,
  sym_title_page = 30,
  sym_section_title = 31,
  sym_text_block = 32,
  sym_rubric = 33,
  sym_reference = 34,
  sym_reference_plus = 35,
  sym_versical = 36,
  sym_page_break = 37,
  sym_line = 38,
  sym_button = 39,
  sym_lords_prayer = 40,
  aux_sym_source_file_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_continuation_line] = "continuation_line",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_pg] = "pg",
  [anon_sym_COLON] = ":",
  [aux_sym_page_range_token1] = "page_range_token1",
  [anon_sym_tp] = "tp",
  [aux_sym_title_page_token1] = "title_page_token1",
  [anon_sym_st] = "st",
  [aux_sym_section_title_token1] = "section_title_token1",
  [aux_sym_section_title_token2] = "section_title_token2",
  [anon_sym_tb] = "tb",
  [anon_sym_bt] = "bt",
  [anon_sym_r] = "r",
  [anon_sym_ref] = "ref",
  [anon_sym_ref_PLUS] = "ref+",
  [aux_sym_reference_plus_token1] = "reference_plus_token1",
  [anon_sym_v] = "v",
  [aux_sym_versical_token1] = "versical_token1",
  [anon_sym_pb] = "pb",
  [aux_sym_page_break_token1] = "page_break_token1",
  [anon_sym_l] = "l",
  [anon_sym_button] = "button",
  [anon_sym_lords_prayer] = "lords_prayer",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_comment] = "comment",
  [sym_page_range] = "page_range",
  [sym_title_page] = "title_page",
  [sym_section_title] = "section_title",
  [sym_text_block] = "text_block",
  [sym_rubric] = "rubric",
  [sym_reference] = "reference",
  [sym_reference_plus] = "reference_plus",
  [sym_versical] = "versical",
  [sym_page_break] = "page_break",
  [sym_line] = "line",
  [sym_button] = "button",
  [sym_lords_prayer] = "lords_prayer",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_continuation_line] = sym_continuation_line,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_pg] = anon_sym_pg,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_page_range_token1] = aux_sym_page_range_token1,
  [anon_sym_tp] = anon_sym_tp,
  [aux_sym_title_page_token1] = aux_sym_title_page_token1,
  [anon_sym_st] = anon_sym_st,
  [aux_sym_section_title_token1] = aux_sym_section_title_token1,
  [aux_sym_section_title_token2] = aux_sym_section_title_token2,
  [anon_sym_tb] = anon_sym_tb,
  [anon_sym_bt] = anon_sym_bt,
  [anon_sym_r] = anon_sym_r,
  [anon_sym_ref] = anon_sym_ref,
  [anon_sym_ref_PLUS] = anon_sym_ref_PLUS,
  [aux_sym_reference_plus_token1] = aux_sym_reference_plus_token1,
  [anon_sym_v] = anon_sym_v,
  [aux_sym_versical_token1] = aux_sym_versical_token1,
  [anon_sym_pb] = anon_sym_pb,
  [aux_sym_page_break_token1] = aux_sym_page_break_token1,
  [anon_sym_l] = anon_sym_l,
  [anon_sym_button] = anon_sym_button,
  [anon_sym_lords_prayer] = anon_sym_lords_prayer,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_comment] = sym_comment,
  [sym_page_range] = sym_page_range,
  [sym_title_page] = sym_title_page,
  [sym_section_title] = sym_section_title,
  [sym_text_block] = sym_text_block,
  [sym_rubric] = sym_rubric,
  [sym_reference] = sym_reference,
  [sym_reference_plus] = sym_reference_plus,
  [sym_versical] = sym_versical,
  [sym_page_break] = sym_page_break,
  [sym_line] = sym_line,
  [sym_button] = sym_button,
  [sym_lords_prayer] = sym_lords_prayer,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_continuation_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_pg] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_page_range_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_tp] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_title_page_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_st] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_section_title_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_title_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_tb] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_r] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ref] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ref_PLUS] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_reference_plus_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_v] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_versical_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_pb] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_page_break_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_l] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_button] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lords_prayer] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_page_range] = {
    .visible = true,
    .named = true,
  },
  [sym_title_page] = {
    .visible = true,
    .named = true,
  },
  [sym_section_title] = {
    .visible = true,
    .named = true,
  },
  [sym_text_block] = {
    .visible = true,
    .named = true,
  },
  [sym_rubric] = {
    .visible = true,
    .named = true,
  },
  [sym_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_reference_plus] = {
    .visible = true,
    .named = true,
  },
  [sym_versical] = {
    .visible = true,
    .named = true,
  },
  [sym_page_break] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_button] = {
    .visible = true,
    .named = true,
  },
  [sym_lords_prayer] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_citation = 1,
  field_command = 2,
  field_content = 3,
  field_level = 4,
  field_link = 5,
  field_modifiers = 6,
  field_page_number = 7,
  field_range = 8,
  field_speaker = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_citation] = "citation",
  [field_command] = "command",
  [field_content] = "content",
  [field_level] = "level",
  [field_link] = "link",
  [field_modifiers] = "modifiers",
  [field_page_number] = "page_number",
  [field_range] = "range",
  [field_speaker] = "speaker",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 2},
  [8] = {.index = 9, .length = 2},
  [9] = {.index = 11, .length = 3},
  [10] = {.index = 14, .length = 2},
  [11] = {.index = 16, .length = 2},
  [12] = {.index = 18, .length = 2},
  [13] = {.index = 20, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_range, 2},
  [1] =
    {field_content, 2},
  [2] =
    {field_command, 0},
    {field_content, 2},
  [4] =
    {field_citation, 2},
  [5] =
    {field_page_number, 2},
  [6] =
    {field_content, 3},
  [7] =
    {field_content, 4},
    {field_level, 2},
  [9] =
    {field_content, 4},
    {field_modifiers, 2},
  [11] =
    {field_command, 0},
    {field_content, 4},
    {field_modifiers, 2},
  [14] =
    {field_citation, 2},
    {field_content, 4},
  [16] =
    {field_content, 4},
    {field_speaker, 2},
  [18] =
    {field_content, 4},
    {field_link, 2},
  [20] =
    {field_content, 6},
    {field_level, 2},
    {field_modifiers, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '\n', 33,
        '#', 56,
        ':', 62,
        'b', 72,
        'l', 95,
        'p', 6,
        'r', 78,
        's', 21,
        't', 8,
        'v', 87,
        '\t', 1,
        ' ', 1,
        'i', 73,
        'o', 73,
      );
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(3);
      if (('1' <= lookahead && lookahead <= '3')) ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 33,
        '#', 56,
        ':', 62,
        'b', 72,
        'l', 95,
        'p', 6,
        'r', 78,
        's', 21,
        't', 8,
        'v', 87,
        '\t', 1,
        ' ', 1,
        'i', 73,
        'o', 73,
      );
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(3);
      if (('1' <= lookahead && lookahead <= '3')) ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '_') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 6:
      if (lookahead == 'b') ADVANCE(92);
      if (lookahead == 'g') ADVANCE(60);
      END_STATE();
    case 7:
      if (lookahead == 'b') ADVANCE(92);
      if (lookahead == 'g') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ':' &&
          lookahead != 'l' &&
          lookahead != 'p' &&
          (lookahead < 'r' || 't' < lookahead) &&
          lookahead != 'v') ADVANCE(55);
      END_STATE();
    case 8:
      if (lookahead == 'b') ADVANCE(74);
      if (lookahead == 'p') ADVANCE(65);
      END_STATE();
    case 9:
      if (lookahead == 'b') ADVANCE(74);
      if (lookahead == 'p') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ':' &&
          lookahead != 'l' &&
          (lookahead < 'r' || 't' < lookahead) &&
          lookahead != 'v') ADVANCE(55);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 'f') ADVANCE(81);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(98);
      END_STATE();
    case 14:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(5);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(100);
      END_STATE();
    case 19:
      if (lookahead == 's') ADVANCE(4);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(76);
      if (lookahead == 'u') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ':' &&
          lookahead != 'b' &&
          lookahead != 'l' &&
          lookahead != 'p' &&
          (lookahead < 'r' || 'v' < lookahead)) ADVANCE(55);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(70);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ':' &&
          lookahead != 'b' &&
          lookahead != 'l' &&
          lookahead != 'p' &&
          (lookahead < 'r' || 't' < lookahead) &&
          lookahead != 'v') ADVANCE(55);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == 'y') ADVANCE(11);
      END_STATE();
    case 26:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead == 'b' ||
          lookahead == 'i' ||
          lookahead == 'o') ADVANCE(68);
      if (('1' <= lookahead && lookahead <= '3')) ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(69);
      END_STATE();
    case 27:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(86);
      END_STATE();
    case 28:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 30:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '\n', 33,
        '#', 56,
        'b', 20,
        'l', 97,
        'p', 7,
        'r', 80,
        's', 22,
        't', 9,
        'v', 89,
        '\t', 35,
        ' ', 35,
      );
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(34);
      if (lookahead != 0) ADVANCE(55);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '#') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '#') ADVANCE(55);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(55);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_continuation_line);
      ADVANCE_MAP(
        '#', 55,
        'b', 50,
        'l', 96,
        'p', 38,
        'r', 79,
        's', 51,
        't', 39,
        'v', 88,
        '\t', 35,
        ' ', 35,
      );
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(34);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(55);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead == '_') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead == 'a') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead == 'b') ADVANCE(93);
      if (lookahead == 'g') ADVANCE(61);
      if (lookahead == ':' ||
          lookahead == 'l' ||
          lookahead == 'p' ||
          ('r' <= lookahead && lookahead <= 't') ||
          lookahead == 'v') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead == 'b') ADVANCE(75);
      if (lookahead == 'p') ADVANCE(66);
      if (lookahead == ':' ||
          lookahead == 'l' ||
          ('r' <= lookahead && lookahead <= 't') ||
          lookahead == 'v') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead == 'd') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead == 'e') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead == 'f') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead == 'n') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead == 'o') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead == 'p') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead == 'r') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead == 'r') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead == 'r') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead == 's') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_continuation_line);
      ADVANCE_MAP(
        't', 77,
        'u', 53,
        ':', 55,
        'b', 55,
        'l', 55,
        'p', 55,
        'r', 55,
        's', 55,
        'v', 55,
      );
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead == 't') ADVANCE(71);
      if (lookahead == ':' ||
          lookahead == 'b' ||
          lookahead == 'l' ||
          lookahead == 'p' ||
          lookahead == 'r' ||
          lookahead == 's' ||
          lookahead == 'v') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead == 't') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead == 't') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead == 'y') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_continuation_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead == 'b' ||
          lookahead == 'i' ||
          lookahead == 'o') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == 'b' ||
          lookahead == 'i' ||
          lookahead == 'o') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_pg);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_pg);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_page_range_token1);
      if (lookahead == '-') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_page_range_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_tp);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_tp);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_title_page_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead == 'b' ||
          lookahead == 'i' ||
          lookahead == 'o') ADVANCE(68);
      if (('1' <= lookahead && lookahead <= '3')) ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(69);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_title_page_token1);
      if (lookahead == 'b' ||
          lookahead == 'i' ||
          lookahead == 'o') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(69);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_title_page_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_st);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_st);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_section_title_token2);
      if (lookahead == 't') ADVANCE(76);
      if (lookahead == 'u') ADVANCE(24);
      if (lookahead == 'b' ||
          lookahead == 'i' ||
          lookahead == 'o') ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_section_title_token2);
      if (lookahead == 'b' ||
          lookahead == 'i' ||
          lookahead == 'o') ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_tb);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_tb);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_bt);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_bt);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_r);
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_r);
      if (lookahead == 'e') ADVANCE(42);
      if (lookahead == ':' ||
          lookahead == 'b' ||
          lookahead == 'l' ||
          lookahead == 'p' ||
          ('r' <= lookahead && lookahead <= 't') ||
          lookahead == 'v') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_r);
      if (lookahead == 'e') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ':' &&
          lookahead != 'b' &&
          lookahead != 'l' &&
          lookahead != 'p' &&
          (lookahead < 'r' || 't' < lookahead) &&
          lookahead != 'v') ADVANCE(55);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_ref);
      if (lookahead == '+') ADVANCE(83);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_ref);
      if (lookahead == '+') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_ref_PLUS);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_ref_PLUS);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_reference_plus_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(86);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_reference_plus_token1);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_v);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_v);
      if (lookahead == ':' ||
          lookahead == 'b' ||
          lookahead == 'l' ||
          lookahead == 'p' ||
          ('r' <= lookahead && lookahead <= 't') ||
          lookahead == 'v') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_v);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ':' &&
          lookahead != 'b' &&
          lookahead != 'l' &&
          lookahead != 'p' &&
          (lookahead < 'r' || 't' < lookahead) &&
          lookahead != 'v') ADVANCE(55);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_versical_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(91);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_versical_token1);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_pb);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_pb);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_page_break_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_l);
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_l);
      if (lookahead == 'o') ADVANCE(46);
      if (lookahead == ':' ||
          lookahead == 'b' ||
          lookahead == 'l' ||
          lookahead == 'p' ||
          ('r' <= lookahead && lookahead <= 't') ||
          lookahead == 'v') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_l);
      if (lookahead == 'o') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ':' &&
          lookahead != 'b' &&
          lookahead != 'l' &&
          lookahead != 'o' &&
          lookahead != 'p' &&
          (lookahead < 'r' || 't' < lookahead) &&
          lookahead != 'v') ADVANCE(55);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_button);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_button);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_lords_prayer);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_lords_prayer);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 30},
  [2] = {.lex_state = 30},
  [3] = {.lex_state = 30},
  [4] = {.lex_state = 30},
  [5] = {.lex_state = 26},
  [6] = {.lex_state = 57},
  [7] = {.lex_state = 90},
  [8] = {.lex_state = 57},
  [9] = {.lex_state = 90},
  [10] = {.lex_state = 57},
  [11] = {.lex_state = 26},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 57},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 26},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 26},
  [24] = {.lex_state = 27},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 28},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 57},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 57},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 26},
  [52] = {.lex_state = 57},
  [53] = {.lex_state = 57},
  [54] = {.lex_state = 26},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 57},
  [57] = {.lex_state = 57},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 57},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 26},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(1),
    [anon_sym_pg] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_page_range_token1] = ACTIONS(1),
    [anon_sym_tp] = ACTIONS(1),
    [anon_sym_st] = ACTIONS(1),
    [aux_sym_section_title_token1] = ACTIONS(1),
    [aux_sym_section_title_token2] = ACTIONS(1),
    [anon_sym_tb] = ACTIONS(1),
    [anon_sym_bt] = ACTIONS(1),
    [anon_sym_r] = ACTIONS(1),
    [anon_sym_ref] = ACTIONS(1),
    [anon_sym_ref_PLUS] = ACTIONS(1),
    [anon_sym_v] = ACTIONS(1),
    [anon_sym_pb] = ACTIONS(1),
    [aux_sym_page_break_token1] = ACTIONS(1),
    [anon_sym_l] = ACTIONS(1),
    [anon_sym_button] = ACTIONS(1),
    [anon_sym_lords_prayer] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(14),
    [sym__line] = STATE(15),
    [sym_comment] = STATE(15),
    [sym_page_range] = STATE(15),
    [sym_title_page] = STATE(15),
    [sym_section_title] = STATE(15),
    [sym_text_block] = STATE(15),
    [sym_rubric] = STATE(15),
    [sym_reference] = STATE(15),
    [sym_reference_plus] = STATE(15),
    [sym_versical] = STATE(15),
    [sym_page_break] = STATE(15),
    [sym_line] = STATE(15),
    [sym_button] = STATE(15),
    [sym_lords_prayer] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [sym_continuation_line] = ACTIONS(7),
    [aux_sym_comment_token1] = ACTIONS(9),
    [anon_sym_pg] = ACTIONS(11),
    [anon_sym_tp] = ACTIONS(13),
    [anon_sym_st] = ACTIONS(15),
    [anon_sym_tb] = ACTIONS(17),
    [anon_sym_bt] = ACTIONS(17),
    [anon_sym_r] = ACTIONS(19),
    [anon_sym_ref] = ACTIONS(21),
    [anon_sym_ref_PLUS] = ACTIONS(23),
    [anon_sym_v] = ACTIONS(25),
    [anon_sym_pb] = ACTIONS(27),
    [anon_sym_l] = ACTIONS(29),
    [anon_sym_button] = ACTIONS(31),
    [anon_sym_lords_prayer] = ACTIONS(33),
  },
  [STATE(2)] = {
    [sym__line] = STATE(15),
    [sym_comment] = STATE(15),
    [sym_page_range] = STATE(15),
    [sym_title_page] = STATE(15),
    [sym_section_title] = STATE(15),
    [sym_text_block] = STATE(15),
    [sym_rubric] = STATE(15),
    [sym_reference] = STATE(15),
    [sym_reference_plus] = STATE(15),
    [sym_versical] = STATE(15),
    [sym_page_break] = STATE(15),
    [sym_line] = STATE(15),
    [sym_button] = STATE(15),
    [sym_lords_prayer] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(35),
    [anon_sym_LF] = ACTIONS(37),
    [sym_continuation_line] = ACTIONS(7),
    [aux_sym_comment_token1] = ACTIONS(9),
    [anon_sym_pg] = ACTIONS(11),
    [anon_sym_tp] = ACTIONS(13),
    [anon_sym_st] = ACTIONS(15),
    [anon_sym_tb] = ACTIONS(17),
    [anon_sym_bt] = ACTIONS(17),
    [anon_sym_r] = ACTIONS(19),
    [anon_sym_ref] = ACTIONS(21),
    [anon_sym_ref_PLUS] = ACTIONS(23),
    [anon_sym_v] = ACTIONS(25),
    [anon_sym_pb] = ACTIONS(27),
    [anon_sym_l] = ACTIONS(29),
    [anon_sym_button] = ACTIONS(31),
    [anon_sym_lords_prayer] = ACTIONS(33),
  },
  [STATE(3)] = {
    [sym__line] = STATE(15),
    [sym_comment] = STATE(15),
    [sym_page_range] = STATE(15),
    [sym_title_page] = STATE(15),
    [sym_section_title] = STATE(15),
    [sym_text_block] = STATE(15),
    [sym_rubric] = STATE(15),
    [sym_reference] = STATE(15),
    [sym_reference_plus] = STATE(15),
    [sym_versical] = STATE(15),
    [sym_page_break] = STATE(15),
    [sym_line] = STATE(15),
    [sym_button] = STATE(15),
    [sym_lords_prayer] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(39),
    [anon_sym_LF] = ACTIONS(41),
    [sym_continuation_line] = ACTIONS(44),
    [aux_sym_comment_token1] = ACTIONS(47),
    [anon_sym_pg] = ACTIONS(50),
    [anon_sym_tp] = ACTIONS(53),
    [anon_sym_st] = ACTIONS(56),
    [anon_sym_tb] = ACTIONS(59),
    [anon_sym_bt] = ACTIONS(59),
    [anon_sym_r] = ACTIONS(62),
    [anon_sym_ref] = ACTIONS(65),
    [anon_sym_ref_PLUS] = ACTIONS(68),
    [anon_sym_v] = ACTIONS(71),
    [anon_sym_pb] = ACTIONS(74),
    [anon_sym_l] = ACTIONS(77),
    [anon_sym_button] = ACTIONS(80),
    [anon_sym_lords_prayer] = ACTIONS(83),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(86), 16,
      anon_sym_LF,
      sym_continuation_line,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [22] = 3,
    ACTIONS(88), 1,
      aux_sym_title_page_token1,
    ACTIONS(90), 1,
      aux_sym_section_title_token1,
    ACTIONS(92), 1,
      aux_sym_section_title_token2,
  [32] = 2,
    ACTIONS(94), 1,
      aux_sym_comment_token2,
    ACTIONS(96), 1,
      aux_sym_section_title_token2,
  [39] = 2,
    ACTIONS(98), 1,
      anon_sym_COLON,
    ACTIONS(100), 1,
      aux_sym_versical_token1,
  [46] = 2,
    ACTIONS(102), 1,
      aux_sym_comment_token2,
    ACTIONS(104), 1,
      aux_sym_section_title_token2,
  [53] = 2,
    ACTIONS(106), 1,
      anon_sym_COLON,
    ACTIONS(108), 1,
      aux_sym_versical_token1,
  [60] = 2,
    ACTIONS(110), 1,
      aux_sym_comment_token2,
    ACTIONS(112), 1,
      aux_sym_section_title_token2,
  [67] = 2,
    ACTIONS(114), 1,
      aux_sym_title_page_token1,
    ACTIONS(116), 1,
      aux_sym_section_title_token2,
  [74] = 1,
    ACTIONS(118), 1,
      anon_sym_LF,
  [78] = 1,
    ACTIONS(120), 1,
      anon_sym_COLON,
  [82] = 1,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
  [86] = 1,
    ACTIONS(124), 1,
      anon_sym_LF,
  [90] = 1,
    ACTIONS(126), 1,
      aux_sym_comment_token2,
  [94] = 1,
    ACTIONS(128), 1,
      anon_sym_LF,
  [98] = 1,
    ACTIONS(130), 1,
      aux_sym_page_range_token1,
  [102] = 1,
    ACTIONS(132), 1,
      aux_sym_title_page_token1,
  [106] = 1,
    ACTIONS(134), 1,
      anon_sym_COLON,
  [110] = 1,
    ACTIONS(136), 1,
      anon_sym_COLON,
  [114] = 1,
    ACTIONS(138), 1,
      anon_sym_COLON,
  [118] = 1,
    ACTIONS(140), 1,
      aux_sym_title_page_token1,
  [122] = 1,
    ACTIONS(142), 1,
      aux_sym_reference_plus_token1,
  [126] = 1,
    ACTIONS(144), 1,
      anon_sym_COLON,
  [130] = 1,
    ACTIONS(146), 1,
      aux_sym_page_break_token1,
  [134] = 1,
    ACTIONS(148), 1,
      anon_sym_COLON,
  [138] = 1,
    ACTIONS(150), 1,
      anon_sym_COLON,
  [142] = 1,
    ACTIONS(152), 1,
      anon_sym_LF,
  [146] = 1,
    ACTIONS(154), 1,
      anon_sym_COLON,
  [150] = 1,
    ACTIONS(156), 1,
      anon_sym_COLON,
  [154] = 1,
    ACTIONS(158), 1,
      anon_sym_LF,
  [158] = 1,
    ACTIONS(160), 1,
      anon_sym_LF,
  [162] = 1,
    ACTIONS(162), 1,
      anon_sym_LF,
  [166] = 1,
    ACTIONS(164), 1,
      anon_sym_COLON,
  [170] = 1,
    ACTIONS(166), 1,
      anon_sym_COLON,
  [174] = 1,
    ACTIONS(168), 1,
      anon_sym_LF,
  [178] = 1,
    ACTIONS(170), 1,
      anon_sym_COLON,
  [182] = 1,
    ACTIONS(172), 1,
      anon_sym_COLON,
  [186] = 1,
    ACTIONS(174), 1,
      anon_sym_COLON,
  [190] = 1,
    ACTIONS(176), 1,
      anon_sym_LF,
  [194] = 1,
    ACTIONS(178), 1,
      anon_sym_COLON,
  [198] = 1,
    ACTIONS(180), 1,
      aux_sym_comment_token2,
  [202] = 1,
    ACTIONS(182), 1,
      anon_sym_COLON,
  [206] = 1,
    ACTIONS(184), 1,
      anon_sym_LF,
  [210] = 1,
    ACTIONS(186), 1,
      anon_sym_LF,
  [214] = 1,
    ACTIONS(188), 1,
      anon_sym_COLON,
  [218] = 1,
    ACTIONS(190), 1,
      aux_sym_comment_token2,
  [222] = 1,
    ACTIONS(192), 1,
      anon_sym_COLON,
  [226] = 1,
    ACTIONS(194), 1,
      anon_sym_COLON,
  [230] = 1,
    ACTIONS(196), 1,
      aux_sym_title_page_token1,
  [234] = 1,
    ACTIONS(198), 1,
      aux_sym_comment_token2,
  [238] = 1,
    ACTIONS(200), 1,
      aux_sym_comment_token2,
  [242] = 1,
    ACTIONS(202), 1,
      aux_sym_title_page_token1,
  [246] = 1,
    ACTIONS(204), 1,
      anon_sym_LF,
  [250] = 1,
    ACTIONS(206), 1,
      aux_sym_comment_token2,
  [254] = 1,
    ACTIONS(208), 1,
      aux_sym_comment_token2,
  [258] = 1,
    ACTIONS(210), 1,
      anon_sym_LF,
  [262] = 1,
    ACTIONS(212), 1,
      aux_sym_comment_token2,
  [266] = 1,
    ACTIONS(214), 1,
      anon_sym_LF,
  [270] = 1,
    ACTIONS(216), 1,
      anon_sym_COLON,
  [274] = 1,
    ACTIONS(218), 1,
      anon_sym_LF,
  [278] = 1,
    ACTIONS(220), 1,
      anon_sym_LF,
  [282] = 1,
    ACTIONS(222), 1,
      anon_sym_LF,
  [286] = 1,
    ACTIONS(224), 1,
      anon_sym_LF,
  [290] = 1,
    ACTIONS(226), 1,
      anon_sym_LF,
  [294] = 1,
    ACTIONS(228), 1,
      anon_sym_LF,
  [298] = 1,
    ACTIONS(230), 1,
      anon_sym_LF,
  [302] = 1,
    ACTIONS(232), 1,
      aux_sym_title_page_token1,
  [306] = 1,
    ACTIONS(234), 1,
      anon_sym_LF,
  [310] = 1,
    ACTIONS(236), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 22,
  [SMALL_STATE(6)] = 32,
  [SMALL_STATE(7)] = 39,
  [SMALL_STATE(8)] = 46,
  [SMALL_STATE(9)] = 53,
  [SMALL_STATE(10)] = 60,
  [SMALL_STATE(11)] = 67,
  [SMALL_STATE(12)] = 74,
  [SMALL_STATE(13)] = 78,
  [SMALL_STATE(14)] = 82,
  [SMALL_STATE(15)] = 86,
  [SMALL_STATE(16)] = 90,
  [SMALL_STATE(17)] = 94,
  [SMALL_STATE(18)] = 98,
  [SMALL_STATE(19)] = 102,
  [SMALL_STATE(20)] = 106,
  [SMALL_STATE(21)] = 110,
  [SMALL_STATE(22)] = 114,
  [SMALL_STATE(23)] = 118,
  [SMALL_STATE(24)] = 122,
  [SMALL_STATE(25)] = 126,
  [SMALL_STATE(26)] = 130,
  [SMALL_STATE(27)] = 134,
  [SMALL_STATE(28)] = 138,
  [SMALL_STATE(29)] = 142,
  [SMALL_STATE(30)] = 146,
  [SMALL_STATE(31)] = 150,
  [SMALL_STATE(32)] = 154,
  [SMALL_STATE(33)] = 158,
  [SMALL_STATE(34)] = 162,
  [SMALL_STATE(35)] = 166,
  [SMALL_STATE(36)] = 170,
  [SMALL_STATE(37)] = 174,
  [SMALL_STATE(38)] = 178,
  [SMALL_STATE(39)] = 182,
  [SMALL_STATE(40)] = 186,
  [SMALL_STATE(41)] = 190,
  [SMALL_STATE(42)] = 194,
  [SMALL_STATE(43)] = 198,
  [SMALL_STATE(44)] = 202,
  [SMALL_STATE(45)] = 206,
  [SMALL_STATE(46)] = 210,
  [SMALL_STATE(47)] = 214,
  [SMALL_STATE(48)] = 218,
  [SMALL_STATE(49)] = 222,
  [SMALL_STATE(50)] = 226,
  [SMALL_STATE(51)] = 230,
  [SMALL_STATE(52)] = 234,
  [SMALL_STATE(53)] = 238,
  [SMALL_STATE(54)] = 242,
  [SMALL_STATE(55)] = 246,
  [SMALL_STATE(56)] = 250,
  [SMALL_STATE(57)] = 254,
  [SMALL_STATE(58)] = 258,
  [SMALL_STATE(59)] = 262,
  [SMALL_STATE(60)] = 266,
  [SMALL_STATE(61)] = 270,
  [SMALL_STATE(62)] = 274,
  [SMALL_STATE(63)] = 278,
  [SMALL_STATE(64)] = 282,
  [SMALL_STATE(65)] = 286,
  [SMALL_STATE(66)] = 290,
  [SMALL_STATE(67)] = 294,
  [SMALL_STATE(68)] = 298,
  [SMALL_STATE(69)] = 302,
  [SMALL_STATE(70)] = 306,
  [SMALL_STATE(71)] = 310,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rubric, 3, 0, 2),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [122] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lords_prayer, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_page_range, 3, 0, 1),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_page, 3, 0, 2),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_title, 3, 0, 2),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_block, 3, 0, 3),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference, 3, 0, 4),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_page_break, 3, 0, 5),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 3, 0, 2),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_versical, 4, 0, 6),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_button, 4, 0, 6),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_title, 5, 0, 7),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_title, 5, 0, 8),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_block, 5, 0, 9),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rubric, 5, 0, 8),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference_plus, 5, 0, 10),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_versical, 5, 0, 11),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 5, 0, 8),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_button, 5, 0, 12),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_title, 7, 0, 13),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dpb(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "dpb",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
