/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 88
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_comment_token1 = 1,
  aux_sym_comment_token2 = 2,
  anon_sym_LF = 3,
  anon_sym_pg = 4,
  anon_sym_COLON = 5,
  aux_sym_page_range_token1 = 6,
  anon_sym_tp = 7,
  aux_sym_title_page_token1 = 8,
  anon_sym_st = 9,
  aux_sym_section_title_token1 = 10,
  aux_sym_section_title_token2 = 11,
  anon_sym_tb = 12,
  anon_sym_bt = 13,
  aux_sym_text_block_token1 = 14,
  anon_sym_r = 15,
  anon_sym_ref = 16,
  anon_sym_ref_PLUS = 17,
  aux_sym_reference_plus_token1 = 18,
  anon_sym_v = 19,
  aux_sym_versical_token1 = 20,
  anon_sym_pb = 21,
  aux_sym_page_break_token1 = 22,
  anon_sym_l = 23,
  anon_sym_button = 24,
  anon_sym_lords_prayer = 25,
  sym_blank_line = 26,
  sym_source_file = 27,
  sym__line = 28,
  sym_comment = 29,
  sym_page_range = 30,
  sym_title_page = 31,
  sym_section_title = 32,
  sym_text_block = 33,
  sym_rubric = 34,
  sym_reference = 35,
  sym_reference_plus = 36,
  sym_versical = 37,
  sym_page_break = 38,
  sym_line = 39,
  sym_button = 40,
  sym_lords_prayer = 41,
  aux_sym_source_file_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_LF] = "\n",
  [anon_sym_pg] = "pg",
  [anon_sym_COLON] = ":",
  [aux_sym_page_range_token1] = "page_range_token1",
  [anon_sym_tp] = "tp",
  [aux_sym_title_page_token1] = "title_page_token1",
  [anon_sym_st] = "st",
  [aux_sym_section_title_token1] = "section_title_token1",
  [aux_sym_section_title_token2] = "section_title_token2",
  [anon_sym_tb] = "tb",
  [anon_sym_bt] = "bt",
  [aux_sym_text_block_token1] = "text_block_token1",
  [anon_sym_r] = "r",
  [anon_sym_ref] = "ref",
  [anon_sym_ref_PLUS] = "ref+",
  [aux_sym_reference_plus_token1] = "reference_plus_token1",
  [anon_sym_v] = "v",
  [aux_sym_versical_token1] = "versical_token1",
  [anon_sym_pb] = "pb",
  [aux_sym_page_break_token1] = "page_break_token1",
  [anon_sym_l] = "l",
  [anon_sym_button] = "button",
  [anon_sym_lords_prayer] = "lords_prayer",
  [sym_blank_line] = "blank_line",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_comment] = "comment",
  [sym_page_range] = "page_range",
  [sym_title_page] = "title_page",
  [sym_section_title] = "section_title",
  [sym_text_block] = "text_block",
  [sym_rubric] = "rubric",
  [sym_reference] = "reference",
  [sym_reference_plus] = "reference_plus",
  [sym_versical] = "versical",
  [sym_page_break] = "page_break",
  [sym_line] = "line",
  [sym_button] = "button",
  [sym_lords_prayer] = "lords_prayer",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_pg] = anon_sym_pg,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_page_range_token1] = aux_sym_page_range_token1,
  [anon_sym_tp] = anon_sym_tp,
  [aux_sym_title_page_token1] = aux_sym_title_page_token1,
  [anon_sym_st] = anon_sym_st,
  [aux_sym_section_title_token1] = aux_sym_section_title_token1,
  [aux_sym_section_title_token2] = aux_sym_section_title_token2,
  [anon_sym_tb] = anon_sym_tb,
  [anon_sym_bt] = anon_sym_bt,
  [aux_sym_text_block_token1] = aux_sym_text_block_token1,
  [anon_sym_r] = anon_sym_r,
  [anon_sym_ref] = anon_sym_ref,
  [anon_sym_ref_PLUS] = anon_sym_ref_PLUS,
  [aux_sym_reference_plus_token1] = aux_sym_reference_plus_token1,
  [anon_sym_v] = anon_sym_v,
  [aux_sym_versical_token1] = aux_sym_versical_token1,
  [anon_sym_pb] = anon_sym_pb,
  [aux_sym_page_break_token1] = aux_sym_page_break_token1,
  [anon_sym_l] = anon_sym_l,
  [anon_sym_button] = anon_sym_button,
  [anon_sym_lords_prayer] = anon_sym_lords_prayer,
  [sym_blank_line] = sym_blank_line,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_comment] = sym_comment,
  [sym_page_range] = sym_page_range,
  [sym_title_page] = sym_title_page,
  [sym_section_title] = sym_section_title,
  [sym_text_block] = sym_text_block,
  [sym_rubric] = sym_rubric,
  [sym_reference] = sym_reference,
  [sym_reference_plus] = sym_reference_plus,
  [sym_versical] = sym_versical,
  [sym_page_break] = sym_page_break,
  [sym_line] = sym_line,
  [sym_button] = sym_button,
  [sym_lords_prayer] = sym_lords_prayer,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pg] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_page_range_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_tp] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_title_page_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_st] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_section_title_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_title_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_tb] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bt] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_text_block_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_r] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ref] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ref_PLUS] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_reference_plus_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_v] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_versical_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_pb] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_page_break_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_l] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_button] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lords_prayer] = {
    .visible = true,
    .named = false,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_page_range] = {
    .visible = true,
    .named = true,
  },
  [sym_title_page] = {
    .visible = true,
    .named = true,
  },
  [sym_section_title] = {
    .visible = true,
    .named = true,
  },
  [sym_text_block] = {
    .visible = true,
    .named = true,
  },
  [sym_rubric] = {
    .visible = true,
    .named = true,
  },
  [sym_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_reference_plus] = {
    .visible = true,
    .named = true,
  },
  [sym_versical] = {
    .visible = true,
    .named = true,
  },
  [sym_page_break] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_button] = {
    .visible = true,
    .named = true,
  },
  [sym_lords_prayer] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '#', 32,
        ':', 40,
        'b', 50,
        'l', 65,
        'p', 11,
        'r', 55,
        's', 24,
        't', 12,
        'v', 60,
        'i', 49,
        'o', 49,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 68,
        '#', 32,
        'b', 23,
        'l', 65,
        'p', 11,
        'r', 55,
        's', 24,
        't', 12,
        'v', 60,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '#', 32,
        ':', 40,
        'b', 50,
        'l', 65,
        'p', 11,
        'r', 55,
        's', 24,
        't', 12,
        'v', 60,
        'i', 49,
        'o', 49,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == 'b' ||
          lookahead == 'i' ||
          lookahead == 'o') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(38);
      if (lookahead == 'b' ||
          lookahead == 'i' ||
          lookahead == 'o') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      END_STATE();
    case 9:
      if (lookahead == '_') ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead == 'b') ADVANCE(63);
      if (lookahead == 'g') ADVANCE(36);
      END_STATE();
    case 12:
      if (lookahead == 'b') ADVANCE(52);
      if (lookahead == 'p') ADVANCE(44);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(56);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(66);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(20);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(67);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(53);
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 27:
      if (lookahead == 'y') ADVANCE(14);
      END_STATE();
    case 28:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(59);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 30:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '\n', 68,
        '#', 32,
        'b', 23,
        'l', 65,
        'p', 11,
        'r', 55,
        's', 24,
        't', 12,
        'v', 60,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_pg);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == 'b' ||
          lookahead == 'i' ||
          lookahead == 'o') ADVANCE(49);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == 'b' ||
          lookahead == 'i' ||
          lookahead == 'o') ADVANCE(49);
      if (('1' <= lookahead && lookahead <= '3')) ADVANCE(48);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == 'b' ||
          lookahead == 'i' ||
          lookahead == 'o') ADVANCE(51);
      if (('1' <= lookahead && lookahead <= '3')) ADVANCE(48);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == 'b' ||
          lookahead == 'i' ||
          lookahead == 'o') ADVANCE(54);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_page_range_token1);
      if (lookahead == '-') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_page_range_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_tp);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_title_page_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_title_page_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_st);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_section_title_token1);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_section_title_token2);
      if (lookahead == ':') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_section_title_token2);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == 't') ADVANCE(53);
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_section_title_token2);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == 'b' ||
          lookahead == 'i' ||
          lookahead == 'o') ADVANCE(54);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_tb);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_bt);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_text_block_token1);
      if (lookahead == 'b' ||
          lookahead == 'i' ||
          lookahead == 'o') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_r);
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_ref);
      if (lookahead == '+') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_ref_PLUS);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_reference_plus_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(59);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_reference_plus_token1);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_v);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_versical_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_versical_token1);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_pb);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_page_break_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_l);
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_button);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_lords_prayer);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_blank_line);
      if (lookahead == '\n') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 30},
  [2] = {.lex_state = 30},
  [3] = {.lex_state = 30},
  [4] = {.lex_state = 30},
  [5] = {.lex_state = 30},
  [6] = {.lex_state = 30},
  [7] = {.lex_state = 30},
  [8] = {.lex_state = 30},
  [9] = {.lex_state = 30},
  [10] = {.lex_state = 30},
  [11] = {.lex_state = 30},
  [12] = {.lex_state = 30},
  [13] = {.lex_state = 30},
  [14] = {.lex_state = 30},
  [15] = {.lex_state = 30},
  [16] = {.lex_state = 30},
  [17] = {.lex_state = 30},
  [18] = {.lex_state = 30},
  [19] = {.lex_state = 30},
  [20] = {.lex_state = 30},
  [21] = {.lex_state = 30},
  [22] = {.lex_state = 30},
  [23] = {.lex_state = 30},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 61},
  [28] = {.lex_state = 61},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 28},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 33},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 33},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 33},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 33},
  [48] = {.lex_state = 6},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 33},
  [52] = {.lex_state = 33},
  [53] = {.lex_state = 6},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 6},
  [56] = {.lex_state = 6},
  [57] = {.lex_state = 6},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 6},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 33},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 6},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 33},
  [68] = {.lex_state = 6},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 33},
  [73] = {.lex_state = 6},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 5},
  [77] = {.lex_state = 2},
  [78] = {.lex_state = 3},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 3},
  [81] = {.lex_state = 6},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 6},
  [84] = {.lex_state = 33},
  [85] = {.lex_state = 6},
  [86] = {.lex_state = 33},
  [87] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(1),
    [anon_sym_pg] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_page_range_token1] = ACTIONS(1),
    [anon_sym_tp] = ACTIONS(1),
    [anon_sym_st] = ACTIONS(1),
    [aux_sym_section_title_token1] = ACTIONS(1),
    [aux_sym_section_title_token2] = ACTIONS(1),
    [anon_sym_tb] = ACTIONS(1),
    [anon_sym_bt] = ACTIONS(1),
    [aux_sym_text_block_token1] = ACTIONS(1),
    [anon_sym_r] = ACTIONS(1),
    [anon_sym_ref] = ACTIONS(1),
    [anon_sym_ref_PLUS] = ACTIONS(1),
    [anon_sym_v] = ACTIONS(1),
    [anon_sym_pb] = ACTIONS(1),
    [aux_sym_page_break_token1] = ACTIONS(1),
    [anon_sym_l] = ACTIONS(1),
    [anon_sym_button] = ACTIONS(1),
    [anon_sym_lords_prayer] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(69),
    [sym__line] = STATE(2),
    [sym_comment] = STATE(2),
    [sym_page_range] = STATE(2),
    [sym_title_page] = STATE(2),
    [sym_section_title] = STATE(2),
    [sym_text_block] = STATE(2),
    [sym_rubric] = STATE(2),
    [sym_reference] = STATE(2),
    [sym_reference_plus] = STATE(2),
    [sym_versical] = STATE(2),
    [sym_page_break] = STATE(2),
    [sym_line] = STATE(2),
    [sym_button] = STATE(2),
    [sym_lords_prayer] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_comment_token1] = ACTIONS(5),
    [anon_sym_pg] = ACTIONS(7),
    [anon_sym_tp] = ACTIONS(9),
    [anon_sym_st] = ACTIONS(11),
    [anon_sym_tb] = ACTIONS(13),
    [anon_sym_bt] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_ref] = ACTIONS(17),
    [anon_sym_ref_PLUS] = ACTIONS(19),
    [anon_sym_v] = ACTIONS(21),
    [anon_sym_pb] = ACTIONS(23),
    [anon_sym_l] = ACTIONS(25),
    [anon_sym_button] = ACTIONS(27),
    [anon_sym_lords_prayer] = ACTIONS(29),
    [sym_blank_line] = ACTIONS(31),
  },
  [STATE(2)] = {
    [sym__line] = STATE(3),
    [sym_comment] = STATE(3),
    [sym_page_range] = STATE(3),
    [sym_title_page] = STATE(3),
    [sym_section_title] = STATE(3),
    [sym_text_block] = STATE(3),
    [sym_rubric] = STATE(3),
    [sym_reference] = STATE(3),
    [sym_reference_plus] = STATE(3),
    [sym_versical] = STATE(3),
    [sym_page_break] = STATE(3),
    [sym_line] = STATE(3),
    [sym_button] = STATE(3),
    [sym_lords_prayer] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(33),
    [aux_sym_comment_token1] = ACTIONS(5),
    [anon_sym_pg] = ACTIONS(7),
    [anon_sym_tp] = ACTIONS(9),
    [anon_sym_st] = ACTIONS(11),
    [anon_sym_tb] = ACTIONS(13),
    [anon_sym_bt] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_ref] = ACTIONS(17),
    [anon_sym_ref_PLUS] = ACTIONS(19),
    [anon_sym_v] = ACTIONS(21),
    [anon_sym_pb] = ACTIONS(23),
    [anon_sym_l] = ACTIONS(25),
    [anon_sym_button] = ACTIONS(27),
    [anon_sym_lords_prayer] = ACTIONS(29),
    [sym_blank_line] = ACTIONS(35),
  },
  [STATE(3)] = {
    [sym__line] = STATE(3),
    [sym_comment] = STATE(3),
    [sym_page_range] = STATE(3),
    [sym_title_page] = STATE(3),
    [sym_section_title] = STATE(3),
    [sym_text_block] = STATE(3),
    [sym_rubric] = STATE(3),
    [sym_reference] = STATE(3),
    [sym_reference_plus] = STATE(3),
    [sym_versical] = STATE(3),
    [sym_page_break] = STATE(3),
    [sym_line] = STATE(3),
    [sym_button] = STATE(3),
    [sym_lords_prayer] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(37),
    [aux_sym_comment_token1] = ACTIONS(39),
    [anon_sym_pg] = ACTIONS(42),
    [anon_sym_tp] = ACTIONS(45),
    [anon_sym_st] = ACTIONS(48),
    [anon_sym_tb] = ACTIONS(51),
    [anon_sym_bt] = ACTIONS(51),
    [anon_sym_r] = ACTIONS(54),
    [anon_sym_ref] = ACTIONS(57),
    [anon_sym_ref_PLUS] = ACTIONS(60),
    [anon_sym_v] = ACTIONS(63),
    [anon_sym_pb] = ACTIONS(66),
    [anon_sym_l] = ACTIONS(69),
    [anon_sym_button] = ACTIONS(72),
    [anon_sym_lords_prayer] = ACTIONS(75),
    [sym_blank_line] = ACTIONS(78),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(83), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [21] = 2,
    ACTIONS(85), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(87), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [42] = 2,
    ACTIONS(89), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(91), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [63] = 2,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(95), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [84] = 2,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(99), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [105] = 2,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(103), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [126] = 2,
    ACTIONS(105), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(107), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [147] = 2,
    ACTIONS(109), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(111), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [168] = 2,
    ACTIONS(113), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(115), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [189] = 2,
    ACTIONS(117), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(119), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [210] = 2,
    ACTIONS(121), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(123), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [231] = 2,
    ACTIONS(125), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(127), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [252] = 2,
    ACTIONS(129), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(131), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [273] = 2,
    ACTIONS(133), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(135), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [294] = 2,
    ACTIONS(137), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(139), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [315] = 2,
    ACTIONS(141), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(143), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [336] = 2,
    ACTIONS(145), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(147), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [357] = 2,
    ACTIONS(149), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(151), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [378] = 2,
    ACTIONS(153), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(155), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [399] = 2,
    ACTIONS(157), 2,
      ts_builtin_sym_end,
      sym_blank_line,
    ACTIONS(159), 14,
      aux_sym_comment_token1,
      anon_sym_pg,
      anon_sym_tp,
      anon_sym_st,
      anon_sym_tb,
      anon_sym_bt,
      anon_sym_r,
      anon_sym_ref,
      anon_sym_ref_PLUS,
      anon_sym_v,
      anon_sym_pb,
      anon_sym_l,
      anon_sym_button,
      anon_sym_lords_prayer,
  [420] = 3,
    ACTIONS(161), 1,
      anon_sym_COLON,
    ACTIONS(163), 1,
      aux_sym_section_title_token1,
    ACTIONS(165), 1,
      aux_sym_section_title_token2,
  [430] = 2,
    ACTIONS(167), 1,
      anon_sym_COLON,
    ACTIONS(169), 1,
      aux_sym_text_block_token1,
  [437] = 2,
    ACTIONS(171), 1,
      anon_sym_COLON,
    ACTIONS(173), 1,
      aux_sym_section_title_token2,
  [444] = 2,
    ACTIONS(175), 1,
      anon_sym_COLON,
    ACTIONS(177), 1,
      aux_sym_versical_token1,
  [451] = 2,
    ACTIONS(179), 1,
      anon_sym_COLON,
    ACTIONS(181), 1,
      aux_sym_versical_token1,
  [458] = 2,
    ACTIONS(183), 1,
      anon_sym_COLON,
    ACTIONS(185), 1,
      aux_sym_text_block_token1,
  [465] = 2,
    ACTIONS(187), 1,
      anon_sym_COLON,
    ACTIONS(189), 1,
      aux_sym_text_block_token1,
  [472] = 1,
    ACTIONS(191), 1,
      anon_sym_COLON,
  [476] = 1,
    ACTIONS(193), 1,
      aux_sym_reference_plus_token1,
  [480] = 1,
    ACTIONS(195), 1,
      anon_sym_LF,
  [484] = 1,
    ACTIONS(197), 1,
      aux_sym_comment_token2,
  [488] = 1,
    ACTIONS(199), 1,
      aux_sym_page_break_token1,
  [492] = 1,
    ACTIONS(201), 1,
      anon_sym_LF,
  [496] = 1,
    ACTIONS(203), 1,
      anon_sym_LF,
  [500] = 1,
    ACTIONS(205), 1,
      anon_sym_LF,
  [504] = 1,
    ACTIONS(207), 1,
      aux_sym_title_page_token1,
  [508] = 1,
    ACTIONS(209), 1,
      anon_sym_COLON,
  [512] = 1,
    ACTIONS(211), 1,
      anon_sym_LF,
  [516] = 1,
    ACTIONS(213), 1,
      aux_sym_comment_token2,
  [520] = 1,
    ACTIONS(215), 1,
      anon_sym_LF,
  [524] = 1,
    ACTIONS(217), 1,
      aux_sym_comment_token2,
  [528] = 1,
    ACTIONS(219), 1,
      anon_sym_LF,
  [532] = 1,
    ACTIONS(221), 1,
      anon_sym_COLON,
  [536] = 1,
    ACTIONS(223), 1,
      aux_sym_comment_token2,
  [540] = 1,
    ACTIONS(225), 1,
      anon_sym_COLON,
  [544] = 1,
    ACTIONS(227), 1,
      anon_sym_LF,
  [548] = 1,
    ACTIONS(229), 1,
      anon_sym_LF,
  [552] = 1,
    ACTIONS(231), 1,
      aux_sym_comment_token2,
  [556] = 1,
    ACTIONS(233), 1,
      aux_sym_comment_token2,
  [560] = 1,
    ACTIONS(235), 1,
      anon_sym_COLON,
  [564] = 1,
    ACTIONS(237), 1,
      anon_sym_COLON,
  [568] = 1,
    ACTIONS(239), 1,
      anon_sym_COLON,
  [572] = 1,
    ACTIONS(241), 1,
      anon_sym_COLON,
  [576] = 1,
    ACTIONS(243), 1,
      anon_sym_COLON,
  [580] = 1,
    ACTIONS(245), 1,
      anon_sym_LF,
  [584] = 1,
    ACTIONS(247), 1,
      aux_sym_title_page_token1,
  [588] = 1,
    ACTIONS(249), 1,
      anon_sym_COLON,
  [592] = 1,
    ACTIONS(251), 1,
      anon_sym_LF,
  [596] = 1,
    ACTIONS(253), 1,
      aux_sym_comment_token2,
  [600] = 1,
    ACTIONS(255), 1,
      anon_sym_LF,
  [604] = 1,
    ACTIONS(257), 1,
      anon_sym_COLON,
  [608] = 1,
    ACTIONS(259), 1,
      aux_sym_title_page_token1,
  [612] = 1,
    ACTIONS(261), 1,
      anon_sym_LF,
  [616] = 1,
    ACTIONS(263), 1,
      aux_sym_comment_token2,
  [620] = 1,
    ACTIONS(265), 1,
      anon_sym_COLON,
  [624] = 1,
    ACTIONS(267), 1,
      ts_builtin_sym_end,
  [628] = 1,
    ACTIONS(269), 1,
      anon_sym_LF,
  [632] = 1,
    ACTIONS(271), 1,
      anon_sym_LF,
  [636] = 1,
    ACTIONS(273), 1,
      aux_sym_comment_token2,
  [640] = 1,
    ACTIONS(275), 1,
      anon_sym_COLON,
  [644] = 1,
    ACTIONS(277), 1,
      anon_sym_LF,
  [648] = 1,
    ACTIONS(279), 1,
      anon_sym_LF,
  [652] = 1,
    ACTIONS(281), 1,
      aux_sym_page_range_token1,
  [656] = 1,
    ACTIONS(283), 1,
      anon_sym_LF,
  [660] = 1,
    ACTIONS(285), 1,
      aux_sym_title_page_token1,
  [664] = 1,
    ACTIONS(287), 1,
      anon_sym_LF,
  [668] = 1,
    ACTIONS(289), 1,
      aux_sym_title_page_token1,
  [672] = 1,
    ACTIONS(291), 1,
      anon_sym_COLON,
  [676] = 1,
    ACTIONS(293), 1,
      anon_sym_LF,
  [680] = 1,
    ACTIONS(295), 1,
      anon_sym_COLON,
  [684] = 1,
    ACTIONS(297), 1,
      aux_sym_comment_token2,
  [688] = 1,
    ACTIONS(299), 1,
      anon_sym_COLON,
  [692] = 1,
    ACTIONS(301), 1,
      aux_sym_comment_token2,
  [696] = 1,
    ACTIONS(303), 1,
      aux_sym_title_page_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 21,
  [SMALL_STATE(6)] = 42,
  [SMALL_STATE(7)] = 63,
  [SMALL_STATE(8)] = 84,
  [SMALL_STATE(9)] = 105,
  [SMALL_STATE(10)] = 126,
  [SMALL_STATE(11)] = 147,
  [SMALL_STATE(12)] = 168,
  [SMALL_STATE(13)] = 189,
  [SMALL_STATE(14)] = 210,
  [SMALL_STATE(15)] = 231,
  [SMALL_STATE(16)] = 252,
  [SMALL_STATE(17)] = 273,
  [SMALL_STATE(18)] = 294,
  [SMALL_STATE(19)] = 315,
  [SMALL_STATE(20)] = 336,
  [SMALL_STATE(21)] = 357,
  [SMALL_STATE(22)] = 378,
  [SMALL_STATE(23)] = 399,
  [SMALL_STATE(24)] = 420,
  [SMALL_STATE(25)] = 430,
  [SMALL_STATE(26)] = 437,
  [SMALL_STATE(27)] = 444,
  [SMALL_STATE(28)] = 451,
  [SMALL_STATE(29)] = 458,
  [SMALL_STATE(30)] = 465,
  [SMALL_STATE(31)] = 472,
  [SMALL_STATE(32)] = 476,
  [SMALL_STATE(33)] = 480,
  [SMALL_STATE(34)] = 484,
  [SMALL_STATE(35)] = 488,
  [SMALL_STATE(36)] = 492,
  [SMALL_STATE(37)] = 496,
  [SMALL_STATE(38)] = 500,
  [SMALL_STATE(39)] = 504,
  [SMALL_STATE(40)] = 508,
  [SMALL_STATE(41)] = 512,
  [SMALL_STATE(42)] = 516,
  [SMALL_STATE(43)] = 520,
  [SMALL_STATE(44)] = 524,
  [SMALL_STATE(45)] = 528,
  [SMALL_STATE(46)] = 532,
  [SMALL_STATE(47)] = 536,
  [SMALL_STATE(48)] = 540,
  [SMALL_STATE(49)] = 544,
  [SMALL_STATE(50)] = 548,
  [SMALL_STATE(51)] = 552,
  [SMALL_STATE(52)] = 556,
  [SMALL_STATE(53)] = 560,
  [SMALL_STATE(54)] = 564,
  [SMALL_STATE(55)] = 568,
  [SMALL_STATE(56)] = 572,
  [SMALL_STATE(57)] = 576,
  [SMALL_STATE(58)] = 580,
  [SMALL_STATE(59)] = 584,
  [SMALL_STATE(60)] = 588,
  [SMALL_STATE(61)] = 592,
  [SMALL_STATE(62)] = 596,
  [SMALL_STATE(63)] = 600,
  [SMALL_STATE(64)] = 604,
  [SMALL_STATE(65)] = 608,
  [SMALL_STATE(66)] = 612,
  [SMALL_STATE(67)] = 616,
  [SMALL_STATE(68)] = 620,
  [SMALL_STATE(69)] = 624,
  [SMALL_STATE(70)] = 628,
  [SMALL_STATE(71)] = 632,
  [SMALL_STATE(72)] = 636,
  [SMALL_STATE(73)] = 640,
  [SMALL_STATE(74)] = 644,
  [SMALL_STATE(75)] = 648,
  [SMALL_STATE(76)] = 652,
  [SMALL_STATE(77)] = 656,
  [SMALL_STATE(78)] = 660,
  [SMALL_STATE(79)] = 664,
  [SMALL_STATE(80)] = 668,
  [SMALL_STATE(81)] = 672,
  [SMALL_STATE(82)] = 676,
  [SMALL_STATE(83)] = 680,
  [SMALL_STATE(84)] = 684,
  [SMALL_STATE(85)] = 688,
  [SMALL_STATE(86)] = 692,
  [SMALL_STATE(87)] = 696,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_page_range, 4, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_page_range, 4, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lords_prayer, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lords_prayer, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_page, 4, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_title_page, 4, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_title, 4, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_title, 4, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_block, 4, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text_block, 4, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rubric, 4, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rubric, 4, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference, 4, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reference, 4, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_page_break, 4, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_page_break, 4, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 4, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line, 4, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_title, 5, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_title, 5, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_block, 5, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text_block, 5, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rubric, 5, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rubric, 5, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_versical, 5, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_versical, 5, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 5, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line, 5, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_button, 5, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_button, 5, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_title, 6, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_title, 6, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference_plus, 6, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reference_plus, 6, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_versical, 6, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_versical, 6, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_button, 6, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_button, 6, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [267] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dpb(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
